apiVersion: batch/v1
kind: CronJob
metadata:
  name: kick-admission-webhook
  namespace: openebs
  labels:
    k8s-apps: kick-admission-webhook
spec:
  # Once a week on Sunday early hours
  schedule: "14 3 * * 0"
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            k8s-apps: kick-admission-webhook
        spec:
          serviceAccountName: openebs-cstor-operator
          restartPolicy: Never
          containers:
            - name: cleanup
              # Update this image tag to match Kubernetes version
              image: "bitnami/kubectl:1.27"
              imagePullPolicy: "IfNotPresent"
              command: ["bash"]
              args:
                - "-c"
                - |
                  if ( kubectl get secret openebs-cstor-admission-secret -o 'go-template={{ index .data "app.crt" | base64decode }}' | openssl x509 -checkend 1209600 ) ; then
                    echo "Certificate is still valid"
                  else
                    echo "Certificate expires in the next 14 days, recycling webhook:"
                    echo "Deleting webhook configuration"
                    kubectl delete validatingwebhookconfiguration openebs-cstor-validation-webhook
                    echo "Deleting secret"
                    kubectl delete secret openebs-cstor-admission-secret
                    echo "Restarting admission controller deployment"
                    kubectl rollout restart deployment openebs-cstor-admission-server
                  fi
